# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='用户')),
                ('operator', models.IntegerField(help_text='操作者')),
                ('operation_time', models.DateTimeField(help_text='操作时间')),
                ('operation_type', models.IntegerField(choices=[(0, '打印扣费'), (1, '兑换码充值'), (2, '微信充值'), (3, '支付宝充值'), (4, '后台修改')], default='变动类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='结束余额', max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='paysAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='用户')),
                ('price', models.DecimalField(decimal_places=2, help_text='价格', max_digits=10)),
                ('realprice', models.DecimalField(decimal_places=2, help_text='实际价格', max_digits=10)),
                ('istype', models.IntegerField(choices=[(1, '支付宝'), (2, '微信支付')], help_text='支付渠道')),
                ('paysapi_id', models.TextField(blank=True, help_text='paysAPI 订单号', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(help_text='打印机名称', max_length=128)),
                ('command', models.CharField(default='lp', help_text='打印命令', max_length=128)),
                ('device_name', models.CharField(help_text='设备名称', max_length=128)),
                ('host_name', models.CharField(blank=True, help_text='主机名（可选）', max_length=128, null=True)),
                ('port', models.IntegerField(blank=True, help_text='端口（可选）', null=True)),
                ('username', models.CharField(blank=True, help_text='用户名（可选）', max_length=128, null=True)),
                ('media', models.CharField(help_text='介质命令', max_length=128)),
                ('sides', models.CharField(help_text='双面打印命令', max_length=128)),
                ('number_up', models.CharField(help_text='每页张数命令', max_length=128)),
                ('number_up_layout', models.CharField(help_text='布局命令', max_length=128)),
                ('page_ranges', models.CharField(help_text='页面范围命令', max_length=128)),
                ('copies', models.CharField(help_text='份数命令', max_length=128)),
                ('cost_per_page', models.DecimalField(decimal_places=2, default='0.50', help_text='每页花费', max_digits=10)),
                ('status', models.IntegerField(choices=[(0, '正常打印'), (2, '漏墨'), (10, '打印机未连接'), (11, '缺纸'), (12, '缺墨')], help_text='打印机状态')),
            ],
            options={
                'ordering': ['-id', 'status'],
            },
        ),
        migrations.CreateModel(
            name='PrinterOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(help_text='打印机')),
                ('function', models.CharField(help_text='功能', max_length=128)),
                ('value', models.CharField(help_text='选项', max_length=128)),
                ('description', models.CharField(help_text='描述', max_length=128)),
                ('is_active', models.BooleanField(help_text='是否启用?')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PrintJobs',
            fields=[
                ('orderid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(help_text='所选打印机')),
                ('uid', models.IntegerField(help_text='用户')),
                ('upload', models.FileField(blank=True, default='文件', upload_to='uploads/%Y/%m/%d/')),
                ('file_pages', models.IntegerField(blank=True, help_text='文件页数')),
                ('verify', models.CharField(help_text='校验码', max_length=128)),
                ('sided', models.IntegerField(choices=[(1, '单面打印'), (2, '长边装订双面打印'), (3, '短边装订双面打印')], help_text='双面打印选项')),
                ('number_up', models.IntegerField(default=1, help_text='每张页数')),
                ('number_up_layout', models.CharField(choices=[('tblr', '从上到下，从左到右'), ('tbrl', '从上到下，从右到左'), ('btlr', '从下到上，从左到右'), ('btrl', '从下到上，从右到左')], help_text='布局', max_length=128)),
                ('media', models.CharField(help_text='介质', max_length=128)),
                ('page_ranges', models.CharField(help_text='页面范围', max_length=128)),
                ('copies', models.IntegerField(default=1, help_text='份数')),
                ('print_pages', models.IntegerField(blank=True, help_text='实际打印张数')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='花费', max_digits=10)),
                ('payment', models.IntegerField(blank=True, choices=[(1, '余额支付'), (2, 'paysAPI'), (99, '我是管理员')], help_text='支付方式')),
                ('created_time', models.DateTimeField(help_text='任务创建时间')),
                ('status', models.IntegerField(choices=[(0, '已完成'), (1, '未完成')], help_text='任务状态')),
                ('printed_time', models.DateTimeField(blank=True, help_text='任务打印时间（可选）', null=True)),
            ],
            options={
                'ordering': ['-orderid'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='账户余额', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='兑换码', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, help_text='金额', max_digits=10)),
                ('created_by', models.IntegerField(help_text='创建人')),
                ('created_time', models.DateTimeField(help_text='创建时间')),
                ('is_used', models.BooleanField(help_text='是否使用?')),
                ('used_by', models.IntegerField(blank=True, help_text='使用者（可选）', null=True)),
                ('used_time', models.DateTimeField(blank=True, help_text='使用时间（可选）', null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='paysapi',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PrintJobs'),
        ),
    ]
