# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='page_ranges',
            field=models.CharField(default='-o page-range=', help_text='页面范围命令', max_length=128),
        ),
    ]
