# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171202_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
