# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(help_text='打印机名称', max_length=128)),
                ('command', models.CharField(default='lp', help_text='打印命令', max_length=128)),
                ('device_name', models.CharField(help_text='设备名称', max_length=128)),
                ('host_name', models.CharField(blank=True, help_text='主机名', max_length=128, null=True)),
                ('port', models.IntegerField(blank=True, help_text='端口', null=True)),
                ('username', models.CharField(blank=True, help_text='用户名', max_length=128, null=True)),
                ('media', models.CharField(help_text='介质命令', max_length=128)),
                ('sides', models.CharField(help_text='双面打印命令', max_length=128)),
                ('number_up', models.CharField(help_text='每页张数命令', max_length=128)),
                ('number_up_layout', models.CharField(help_text='布局命令', max_length=128)),
                ('page_ranges', models.CharField(help_text='页面范围命令', max_length=128)),
                ('copies', models.CharField(help_text='份数命令', max_length=128)),
                ('cost_per_page', models.DecimalField(decimal_places=2, default='0.50', help_text='每页花费', max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
