# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171203_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='用户')),
                ('operator', models.IntegerField(help_text='操作者')),
                ('operation_time', models.TimeField(help_text='操作时间')),
                ('operation_type', models.IntegerField(choices=[(0, '打印扣费'), (1, '兑换码充值'), (2, '微信充值'), (3, '支付宝充值'), (4, '后台修改')], default='变动类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='结束余额', max_digits=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='printjobs',
            name='is_printed',
            field=models.BooleanField(help_text='是否打印完成?'),
        ),
        migrations.AlterField(
            model_name='printjobs',
            name='sided',
            field=models.IntegerField(choices=[(1, '单面打印'), (2, '长边装订双面打印'), (3, '短边装订双面打印')], help_text='双面打印选项'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='账户余额', max_digits=10),
        ),
    ]
