# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171203_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['-id', 'status']},
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.IntegerField(choices=[(0, '正常打印'), (2, '漏墨'), (10, '打印机未连接'), (11, '缺纸'), (12, '缺墨')], default=0, help_text='打印机状态'),
            preserve_default=False,
        ),
    ]
